#!/usr/bin/env bash

echo "creating key"
vultr sshkey update 5917fd9d67361 -f ~/.ssh/id_rsa.pub

echo "creating script"
while [ ! -f  "$GHC_SYNC_TOP_DIR""etc/fileserv_rsa.pub" ] ; do
    echo "waiting for fileserv_rsa.pub"
    sleep 60
done
pushd "$GHC_SYNC_TOP_DIR""etc/templates"
echo "fileservkey: $(cat "$GHC_SYNC_TOP_DIR""etc/fileserv_rsa.pub")" | mustache - boot-compserv.mustache > "$GHC_SYNC_TOP_DIR""etc/scripts/boot-compserv"
popd
vultr script update 63694 -f "$GHC_SYNC_TOP_DIR""etc/scripts/boot-compserv"
